# .cpanel.yml
---
deployment:
  tasks:
    - export DEPLOYPATH=/home/omnidevs/almaskosar

    - name: Start deployment
      command: echo "Starting deployment..."

    - name: Change to deployment directory
      command: cd $DEPLOYPATH

    - name: Clone or pull latest code from GitHub
      command: |
        if [ -d "$DEPLOYPATH/.git" ]; then
          git pull origin main
        else
          git clone https://github.com/fzkst/almaskosar_webshop_v2.git $DEPLOYPATH
        fi

    - name: Install composer dependencies
      command: composer install --no-dev --optimize-autoloader

    - name: Copy .env file
      command: |
        if [ ! -f "$DEPLOYPATH/.env" ]; then
          cp $DEPLOYPATH/.env.example $DEPLOYPATH/.env
        fi

    - name: Generate application key
      command: php artisan key:generate

    - name: Run migrations
      command: php artisan migrate --force

    - name: Clear caches
      command: php artisan config:cache && php artisan route:cache && php artisan view:cache

    - name: Install npm dependencies and build assets
      command: |
        npm install
        npm run production

    - name: Finish deployment
      command: echo "Deployment finished."
